Alioth: sepolicy: allow hal_camera_default to read /dev/adsprpc-smd-secure
05-20 17:02:33.678   878  1598 E android.hardware.camera.provider@2.4-service_64: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2459: Error -1: apps_dev_init: app does not have access to fastrpc device of domain 3 (Permission denied)
05-20 17:02:33.678   878  1598 E android.hardware.camera.provider@2.4-service_64: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2588: Error 0xffffffff: apps_dev_init failed for domain 3, errno Permission denied
05-20 17:02:33.672   878   878 W provider@2.4-se: type=1400 audit(0.0:55): avc: denied { read } for name="adsprpc-smd-secure" dev="tmpfs" ino=28876 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:vendor_xdsp_device:s0 tclass=chr_file permissive=0

Signed-off-by: Omkar Chandorkar <gotenksIN@aosip.dev>